{{- if and .Values.grafana.enabled .Values.grafana.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-grafana-storage
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-grafana
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.grafana.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.grafana.persistence.size }}
{{- end }}
