{{- if and .Values.prometheus.enabled .Values.prometheus.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-prometheus-storage
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-prometheus
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.prometheus.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.prometheus.persistence.size }}
{{- end }}
