namespace: es-serverless
resources:
  - ../../base
  - ../../addons/minio
  - ../../addons/hpa
  - ../../addons/snapshot
  - ../../addons/monitoring
  - ../../addons/logging
  - ../../addons/shard-controller
  - ../../addons/reporting
  - ../../addons/backup