apiVersion: v1
kind: Service
metadata:
  name: es-serverless-manager
  namespace: es-serverless
  labels:
    app: es-serverless-manager
spec:
  selector:
    app: es-serverless-manager
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP