apiVersion: v1
kind: ServiceAccount
metadata:
  name: es-serverless-manager
  namespace: es-serverless
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: es-serverless
  name: es-serverless-manager
rules:
- apiGroups: [""]
  resources: ["namespaces", "pods", "services", "configmaps", "secrets", "persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: es-serverless-manager
  namespace: es-serverless
subjects:
- kind: ServiceAccount
  name: es-serverless-manager
  namespace: es-serverless
roleRef:
  kind: Role
  name: es-serverless-manager
  apiGroup: rbac.authorization.k8s.io