{{- if .Values.grafana.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-grafana-datasources
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-grafana
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      {{- range .Values.grafana.datasources }}
      - name: {{ .name }}
        type: {{ .type }}
        url: {{ .url }}
        isDefault: {{ .isDefault }}
        access: {{ .access }}
      {{- end }}
{{- end }}
