{{- if .Values.manager.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-manager
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-manager
    component: manager
    {{- include "control-plane.labels" . | nindent 4 }}
spec:
  type: {{ .Values.manager.service.type }}
  ports:
    - port: {{ .Values.manager.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name }}-manager
    component: manager
{{- end }}
