{{- if and .Values.manager.enabled .Values.manager.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-manager-data
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-manager
    component: manager
    {{- include "control-plane.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.manager.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.manager.persistence.size }}
{{- end }}
