{{- if .Values.reportingService.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-reporting
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-reporting
    component: reporting
    {{- include "control-plane.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.reportingService.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-reporting
      component: reporting
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-reporting
        component: reporting
        {{- include "control-plane.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: reporting
          image: "{{ .Values.reportingService.image.repository }}:{{ .Values.reportingService.image.tag }}"
          imagePullPolicy: {{ .Values.reportingService.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            {{- toYaml .Values.reportingService.env | nindent 12 }}
          resources:
            {{- toYaml .Values.reportingService.resources | nindent 12 }}
{{- end }}
