apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
  namespace: es-serverless
data:
  elasticsearch.yml: |
    cluster.name: es-serverless-cluster
    network.host: 0.0.0.0
    http.port: 9200
    transport.port: 9300
    discovery.type: single-node
    xpack.security.enabled: false
    xpack.monitoring.collection.enabled: true