apiVersion: apps/v1
kind: Deployment
metadata:
  name: es-serverless-manager
  namespace: es-serverless
  labels:
    app: es-serverless-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: es-serverless-manager
  template:
    metadata:
      labels:
        app: es-serverless-manager
    spec:
      serviceAccountName: es-serverless-manager
      containers:
        - name: manager
          image: es-serverless-manager:latest
          ports:
            - containerPort: 8080
          env:
            - name: NAMESPACE
              value: "es-serverless"
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
            limits:
              cpu: "500m"
              memory: "500Mi"